import java.time.YearMonth;
import java.time.Year;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

public class PenghitungHariFrame extends javax.swing.JFrame {

    public PenghitungHariFrame() {
        initComponents();
          // Atur model untuk spinnerTahun
        spinnerTahun.setModel(new javax.swing.SpinnerNumberModel(2024, 1900, 2100, 1));
        
       labelSelisihHari = new javax.swing.JLabel();  // Menggunakan JLabel untuk selisih hari
labelSelisihHari.setFont(new java.awt.Font("Tahoma", 1, 16));
labelSelisihHari.setText("Selisih Hari: ");

        labelHariPertama.setFont(new java.awt.Font("Tahoma", 1, 16));
        labelHariPertama.setText("Hari Pertama: ");

        labelHariTerakhir.setFont(new java.awt.Font("Tahoma", 1, 16));
        labelHariTerakhir.setText("Hari Terakhir: ");
        
        labelSelisihHari.setFont(new java.awt.Font("Tahoma", 1, 16)); // Penambahan label untuk selisih hari
        labelSelisihHari.setText("Selisih Hari: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        labelTahun = new javax.swing.JLabel();
        labelHasil = new javax.swing.JLabel();
        buttonHitung = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        comboBoxBulan = new javax.swing.JComboBox<>();
        spinnerTahun = new javax.swing.JSpinner();
        calendarPilihTanggal = new com.toedter.calendar.JCalendar();
        labelHariPertama = new javax.swing.JLabel();
        labelHariTerakhir = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        labelSelisihHari = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Penghitung Hari");

        labelBulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelBulan.setText("Pilih Bulan");

        labelTahun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTahun.setText("Masukkan Tahun");

        labelHasil.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHasil.setText("Jumlah Hari");

        buttonHitung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonHitung.setText("Hitung jumlah hari");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        buttonKeluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        comboBoxBulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboBoxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        comboBoxBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBulanActionPerformed(evt);
            }
        });

        spinnerTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerTahunStateChanged(evt);
            }
        });

        labelHariPertama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHariPertama.setText("Hari Pertama");

        labelHariTerakhir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHariTerakhir.setText("Hari Terakhir");

        labelSelisihHari.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelSelisihHari.setText("Selisih Hari");

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTahun)
                                    .addComponent(labelBulan))
                                .addGap(68, 68, 68)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(spinnerTahun)
                                            .addComponent(comboBoxBulan, 0, 277, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(calendarPilihTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labelHasil)
                            .addComponent(labelHariPertama))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHariTerakhir)
                            .addComponent(labelSelisihHari))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBulan)
                            .addComponent(comboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTahun)))
                    .addComponent(calendarPilihTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(labelHasil)
                .addGap(57, 57, 57)
                .addComponent(labelHariPertama)
                .addGap(37, 37, 37)
                .addComponent(labelHariTerakhir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSelisihHari)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
       try {
        // Ambil bulan dan tahun
        int bulan = comboBoxBulan.getSelectedIndex() + 1;  // Bulan dimulai dari 1
        int tahun = (int) spinnerTahun.getValue();  // Ambil tahun dari spinner

        // Membuat objek YearMonth untuk bulan dan tahun yang dipilih
        YearMonth yearMonth = YearMonth.of(tahun, bulan);
        int jumlahHari = yearMonth.lengthOfMonth();
        boolean isKabisat = Year.isLeap(tahun);

        // Hitung hari pertama dan terakhir
        int hariPertama = yearMonth.atDay(1).getDayOfWeek().getValue();  // 1 = Senin, 7 = Minggu
        int hariTerakhir = yearMonth.atEndOfMonth().getDayOfWeek().getValue();

        // Ambil tanggal yang dipilih dari JCalendar
        LocalDate selectedDate = calendarPilihTanggal.getDate().toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

        // Debugging: Tampilkan tanggal yang dipilih
        System.out.println("Tanggal yang dipilih: " + selectedDate);

        // Pastikan tanggal yang dipilih valid
        if (selectedDate == null) {
            labelSelisihHari.setText("Tanggal belum dipilih.");
            return;
        }

        // Hitung selisih hari antara tanggal yang dipilih dan tanggal pertama bulan
        LocalDate firstDayOfMonth = yearMonth.atDay(1);
        long selisihHari = ChronoUnit.DAYS.between(firstDayOfMonth, selectedDate);

        // Debugging: Tampilkan selisih hari
        System.out.println("Selisih Hari: " + selisihHari);

        // Tampilkan hasil di labelHasil
        if (isKabisat) {
            labelHasil.setText("Tahun " + tahun + " adalah tahun kabisat. Jumlah Hari: " + jumlahHari);
        } else {
            labelHasil.setText("Tahun " + tahun + " bukan tahun kabisat. Jumlah Hari: " + jumlahHari);
        }

        // Update teks labelHariPertama dan labelHariTerakhir dengan nama hari
        labelHariPertama.setText("Hari Pertama: " + getNamaHari(hariPertama));
        labelHariTerakhir.setText("Hari Terakhir: " + getNamaHari(hariTerakhir));

        // Update teks labelSelisihHari dengan selisih hari
        labelSelisihHari.setText("Selisih Hari: " + selisihHari);  // Update labelSelisihHari

        // Force a repaint of the form to make sure the UI is updated
        revalidate();  // Recalculate the layout
        repaint();     // Redraw the UI
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}

// Fungsi untuk mendapatkan nama hari dari angka
private String getNamaHari(int nilaiHari) {
    switch (nilaiHari) {
        case 1: return "Senin";
        case 2: return "Selasa";
        case 3: return "Rabu";
        case 4: return "Kamis";
        case 5: return "Jumat";
        case 6: return "Sabtu";
        case 7: return "Minggu";
        default: return "";
    }
    }//GEN-LAST:event_buttonHitungActionPerformed

    private void spinnerTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerTahunStateChanged
       buttonHitungActionPerformed(null); // Hitung ulang saat tahun diubah
    }//GEN-LAST:event_spinnerTahunStateChanged

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
      System.exit(0); // Keluar dari aplikasi
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void comboBoxBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBulanActionPerformed
        
    }//GEN-LAST:event_comboBoxBulanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungHariFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JButton buttonKeluar;
    private com.toedter.calendar.JCalendar calendarPilihTanggal;
    private javax.swing.JComboBox<String> comboBoxBulan;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelHariPertama;
    private javax.swing.JLabel labelHariTerakhir;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelSelisihHari;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
